### ISSUE TITLE
Failed to save file.

### ISSUE THREAD

**Issue by davidyuan1013** [Athari/XnaConvert#3]
![_](https://cloud.githubusercontent.com/assets/7736481/3119313/2eda99fa-e745-11e3-8e89-930857144509.jpg)
Can you solve the problem for me?:)
Thanks!

**Comment by Athari** [comment]
This file is written using custom content writer, so it needs custom content reader, `Fds.Framework.Content.Texture2DReader`. Even if it's loaded, it's likely to produce custom texture class, so this case can't be supported without hacking this particular application.

Files from which application are you trying to convert?
