### ISSUE TITLE
Magicka .xnb format

### ISSUE THREAD

**Issue by CA10C3SAR** [Athari/XnaConvert#5]
Athari could you help me read .xnb files from this game:

https://www.youtube.com/watch?v=2nGf7NQW98k

Tried with your convert but dont worked, think they have own format :/

**Comment by Athari** [comment]
I've downloaded Magicka Demo from Steam. This command line seems to work fine:

```
Alba.XnaConvert convert -v 3.1 -r -d "C:\Games\Magicka demo\ContentDemo" -o "C:\Unpacked\MagickaDemo"
```

Note that only textures are supported.
