### ISSUE TITLE
Can't load any "Alba.XnaConvert.Loader.Xna" and the process stopped

### ISSUE THREAD

**Issue by ghost** [Athari/XnaConvert#6]
Could you give an advise about why doesn't work properly for me during the process?
Here you have a screenshot of command prompt and the issue:

http://imagensn.com/images/2015/01/08/Ashampoo_Snap_2015.01.08_23h00m26s_001_Administrador-Simbolodelsistema.png

Information:
- I have all XNA Frameworks installed (1.0-4.0)
- I have Visual Studio Ultimate 2010, 2012 installed
- I have all NET Frameworks installed
- Windows 7 Ultimate (x86)

**Comment by Athari** [comment]
Warning at the top says, "running from untrusted location (Internet)". Before unpacking the zip file, right click it, choose "Properties", then click "Unblock" button at the bottom. It can also happen if you're running the executable from a network location.

**Comment by ghost** [comment]
Looks like that it works, but now I have another different issue (I created other thread).
