### ISSUE TITLE
Failed to save file. Access to the path "any path here" is denied.

### ISSUE THREAD

**Issue by cjay567** [Athari/XnaConvert#9]
I've tried with many different paths, my desktop, the folder where the xnb file is being loaded, a folder named "Unpacked" in the same directory as Alba.XnaConvert.exe, the directory of Alba.XnaConvert.exe, nothing works. And help?

**Comment by Athari** [comment]
Please provide the whole error output.

**Comment by cjay567** [comment]
Nvm fixed it. I didn't specify the file name. I just did -i "filelocation" then -o "directorylocation" instead of "directorylocation\Unpacked.xnb"
